server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaadin
    username: ${DB_VAADIN_USER}
    password: ${DB_VAADIN_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
vaadin:
  servlet:
    closeIdleSessions: false
    heartbeatInterval: 500
    productionMode: true
